// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tensaiSidebar: [{type: 'autogenerated', dirName: 'tensai'}],
  multipacksSidebar: [{type: 'autogenerated', dirName: 'multipacks'}],
  grimoireSidebar: [{type: 'autogenerated', dirName: 'grimoire'}],
};

module.exports = sidebars;
